/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Article = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'sentiment' : IDL.Float64,
});
export const FetchResult = IDL.Record({
  'inr' : IDL.Float64,
  'usd' : IDL.Float64,
  'articles' : IDL.Vec(Article),
  'sentimentAvg' : IDL.Float64,
});
export const PriceSnapshot = IDL.Record({
  'inr' : IDL.Float64,
  'usd' : IDL.Float64,
  'lastUpdated' : IDL.Int,
});
export const Candle = IDL.Record({
  'low' : IDL.Float64,
  'high' : IDL.Float64,
  'close' : IDL.Float64,
  'open' : IDL.Float64,
  'timestamp' : IDL.Int,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'fetchAndUpdatePrice' : IDL.Func([], [FetchResult], []),
  'getLatestPrice' : IDL.Func([], [PriceSnapshot], ['query']),
  'getOHLCHistory' : IDL.Func([], [IDL.Vec(Candle)], ['query']),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Article = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'sentiment' : IDL.Float64,
  });
  const FetchResult = IDL.Record({
    'inr' : IDL.Float64,
    'usd' : IDL.Float64,
    'articles' : IDL.Vec(Article),
    'sentimentAvg' : IDL.Float64,
  });
  const PriceSnapshot = IDL.Record({
    'inr' : IDL.Float64,
    'usd' : IDL.Float64,
    'lastUpdated' : IDL.Int,
  });
  const Candle = IDL.Record({
    'low' : IDL.Float64,
    'high' : IDL.Float64,
    'close' : IDL.Float64,
    'open' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'fetchAndUpdatePrice' : IDL.Func([], [FetchResult], []),
    'getLatestPrice' : IDL.Func([], [PriceSnapshot], ['query']),
    'getOHLCHistory' : IDL.Func([], [IDL.Vec(Candle)], ['query']),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };